apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins # name of the role, we have created.
subjects:
- kind: ServiceAccount
  name: jenkins-sa # name of service account, we have created